version: '3.8'
services:
  cache:
    container_name: redis_container
    image: redis:7.4-alpine
    restart: always
    expose:
      - "6379"
    ports:
      - '6000:6379'
    command: redis-server --save 20 1 --loglevel warning